version: '3.8'

networks:
    global_network:
        external: true

services:
    sample_backend:
        image: 'node:16.15-alpine3.15'
        container_name: sample_backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
        networks:
            - global_network

    # redis:
    #   image: 'redis:alpine'
    #   ports:
    #     - 6379:6379
    #   networks:
    #     - global_network
