version: '3.8'

networks:
    global_network:
        external: true

services:
    backend:
        image: 'node:16.15-alpine3.15'
        container_name: backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
            # - '3003:3003'
        networks:
            - global_network
